### ISSUE TITLE
Remoteabac needs to perform authentication of the caller in addition to TLS encryption

### ISSUE THREAD

**Issue by huang195** [fr8r/fr8r-ansible#130]

**Comment by MikeSpreitzer** [comment]
The wording of this issue sounds like you are saying that the remoteabac process needs to check the authentication of something.  I suspect you mean instead that it needs to do what is necessary to satisfy the authentication requirement of the apiserver.  The system seems to be working now; how can that be if this issue is a problem?  Perhaps some clarification in the issue title and description (i.e., first comment) are in order.

**Comment by MikeSpreitzer** [comment]
Issue moved to [fr8r/fr8r-remoteabac #1](https://github.com/fr8r/fr8r-remoteabac/issues/1) via [**ZenHub**](https://www.zenhub.com/)
